[2024-11-22T16:15:01.023+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-22T16:15:01.037+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_etl_pipeline.transform_task manual__2024-11-22T16:13:02.028598+00:00 [queued]>
[2024-11-22T16:15:01.044+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_etl_pipeline.transform_task manual__2024-11-22T16:13:02.028598+00:00 [queued]>
[2024-11-22T16:15:01.046+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-11-22T16:15:01.070+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform_task> on 2024-11-22 16:13:02.028598+00:00
[2024-11-22T16:15:01.151+0000] {logging_mixin.py:190} WARNING - /home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=50658) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-22T16:15:01.182+0000] {standard_task_runner.py:72} INFO - Started process 50697 to run task
[2024-11-22T16:15:01.173+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_etl_pipeline', 'transform_task', 'manual__2024-11-22T16:13:02.028598+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_extraction.py', '--cfg-path', '/tmp/tmpzkcuzj0f']
[2024-11-22T16:15:01.189+0000] {standard_task_runner.py:105} INFO - Job 40: Subtask transform_task
[2024-11-22T16:15:01.577+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_etl_pipeline.transform_task manual__2024-11-22T16:13:02.028598+00:00 [running]> on host ubuntu
[2024-11-22T16:15:01.816+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Team_14' AIRFLOW_CTX_DAG_ID='weather_data_etl_pipeline' AIRFLOW_CTX_TASK_ID='transform_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T16:13:02.028598+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-22T16:13:02.028598+00:00'
[2024-11-22T16:15:01.828+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-22T16:15:01.836+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-22T16:15:01.839+0000] {logging_mixin.py:190} INFO - Current task name:transform_task state:running start_date:2024-11-22 16:15:01.038467+00:00
[2024-11-22T16:15:01.839+0000] {logging_mixin.py:190} INFO - Dag name:weather_data_etl_pipeline and current dag run status:running
[2024-11-22T16:15:01.840+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-22T16:15:04.974+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/weather-etl-pipeline/dags/weather_data_extraction.py", line 83, in transform_data
    df['Formatted Date'] = df['Formatted Date'].apply(lambda x: parser.parse(x) if isinstance(x, str) else x)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/pandas/core/series.py", line 4924, in apply
    ).apply()
      ^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/pandas/core/apply.py", line 1427, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/pandas/core/apply.py", line 1507, in apply_standard
    mapped = obj._map_values(
             ^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/pandas/core/base.py", line 921, in _map_values
    return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/pandas/core/algorithms.py", line 1743, in map_array
    return lib.map_infer(values, mapper, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib.pyx", line 2972, in pandas._libs.lib.map_infer
  File "/home/vboxuser/airflow/weather-etl-pipeline/dags/weather_data_extraction.py", line 83, in <lambda>
    df['Formatted Date'] = df['Formatted Date'].apply(lambda x: parser.parse(x) if isinstance(x, str) else x)
                                                                ^^^^^^
NameError: name 'parser' is not defined. Did you mean: 'parse'?
[2024-11-22T16:15:05.113+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-22T16:15:05.119+0000] {logging_mixin.py:190} INFO - Task start:2024-11-22 16:15:01.038467+00:00 end:2024-11-22 16:15:05.112652+00:00 duration:4.074185
[2024-11-22T16:15:05.121+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform_task> dag:<DAG: weather_data_etl_pipeline> dagrun:<DagRun weather_data_etl_pipeline @ 2024-11-22 16:13:02.028598+00:00: manual__2024-11-22T16:13:02.028598+00:00, state:running, queued_at: 2024-11-22 16:13:02.386369+00:00. externally triggered: True>
[2024-11-22T16:15:05.121+0000] {logging_mixin.py:190} INFO - Failure caused by name 'parser' is not defined
[2024-11-22T16:15:05.122+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=weather_data_etl_pipeline, task_id=transform_task, run_id=manual__2024-11-22T16:13:02.028598+00:00, execution_date=20241122T161302, start_date=20241122T161501, end_date=20241122T161505
[2024-11-22T16:15:05.233+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-22T16:15:05.233+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 40 for task transform_task (name 'parser' is not defined; 50697)
Traceback (most recent call last):
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/weather-etl-pipeline/dags/weather_data_extraction.py", line 83, in transform_data
    df['Formatted Date'] = df['Formatted Date'].apply(lambda x: parser.parse(x) if isinstance(x, str) else x)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/pandas/core/series.py", line 4924, in apply
    ).apply()
      ^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/pandas/core/apply.py", line 1427, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/pandas/core/apply.py", line 1507, in apply_standard
    mapped = obj._map_values(
             ^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/pandas/core/base.py", line 921, in _map_values
    return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/pandas/core/algorithms.py", line 1743, in map_array
    return lib.map_infer(values, mapper, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib.pyx", line 2972, in pandas._libs.lib.map_infer
  File "/home/vboxuser/airflow/weather-etl-pipeline/dags/weather_data_extraction.py", line 83, in <lambda>
    df['Formatted Date'] = df['Formatted Date'].apply(lambda x: parser.parse(x) if isinstance(x, str) else x)
                                                                ^^^^^^
NameError: name 'parser' is not defined. Did you mean: 'parse'?
[2024-11-22T16:15:05.304+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-22T16:15:05.659+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T16:15:05.801+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
